#!/bin/bash

source lib/constants
source lib/help
source lib/reader
source lib/writer

# main

while [[ 1 -eq 1 ]]; do

  printf "$MAIN_PROMPT"
  read -r cmd

  case $cmd in
    read ) reader ;;
    reader ) reader ;;
    r ) reader ;;
    write ) writer ;;
    writer ) writer ;;
    w ) writer ;;
    quit ) exit 0 ;;
    q ) exit 0 ;;
    help ) help ;;
    h ) help ;;
    * ) ;;
  esac

done

# end
